### ISSUE TITLE
Parse error when a function returns a function.

### ISSUE THREAD

**Issue by Protowalker** [ItsDeltin/Overwatch-Script-To-Workshop#200]
`(Vector => Vector => Vector => Vector => Vector => define) BezierPathCalculation: (Vector p0) => (Vector p1) => (Vector p2) => (Vector p3) => (define t) => ((1-t)^3)*p0 + (3*(1-t)^2)*t*p1 + (3*(1-t)*(t^2)*p2) + (t^3)*p3;`

```
An exception was thrown while translating to workshop.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Deltin.Deltinteger.Parse.Lambda.LambdaHandler.ParseInner(ActionSet actionSet) in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Lambda\PortableBuilder.cs:line 140
   at Deltin.Deltinteger.Parse.FunctionBuilder.FunctionBuildController.Subcall(ActionSet actionSet, IFunctionHandler function) in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Functions\Builder\Builder.cs:line 145
 ```

**Comment by Protowalker** [comment]
Simplest repro:
```
(define => define) Self: (define val) => val;
BigMessage(AllPlayers(), Self(10));
```
Same error.
