### ISSUE TITLE
Error when debugging - Unsure how to handle function 'Hero

### ISSUE THREAD

**Issue by Dogers** [ItsDeltin/Overwatch-Script-To-Workshop#317]
After starting the debugger in VSCode, I'm copying the global target which provides:

```
variables
{
	player:
		1: self_is_using_backup
		3: self_allowed_hero_buff
		4: self_is_baby_dva
}

actions
{
	Event Player.self_is_using_backup = False;
	Event Player.self_allowed_hero_buff = Array(Hero(Reinhardt), Hero(Winston), Hero(Roadhog), Hero(Zarya), Hero(D.Va), Hero(Orisa),
		Hero(Wrecking Ball), Hero(Sigma));
	Event Player.self_is_baby_dva = False;
}
```

The debugger then throws this error in VSCode:

```
OSTW debugger exception: System.Exception: Unsure of how to handle function 'Hero
   at Deltin.Deltinteger.Debugger.DebuggerActionSetResult.Error(String msg) in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Debugger\Debugger.cs:line 134
   at Deltin.Deltinteger.Debugger.DebuggerActionSetResult.PartFromExpression(ITTEExpression expression) in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Debugger\Debugger.cs:line 163
   at Deltin.Deltinteger.Debugger.DebuggerActionSetResult.<PartFromExpression>b__8_0(ITTEExpression v) in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Debugger\Debugger.cs:line 147
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Deltin.Deltinteger.Debugger.DebuggerActionSetResult.PartFromExpression(ITTEExpression expression) in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Debugger\Debugger.cs:line 147
   at Deltin.Deltinteger.Debugger.DebuggerActionSetResult..ctor(Workshop workshop) in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Debugger\Debugger.cs:line 112
   at Deltin.Deltinteger.Debugger.ClipboardListener.Listen() in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Debugger\Debugger.cs:line 58
```

This is with today's OW pachimari update and 2.0-beta14-winx64, in case it's something new added!

**Comment by ItsDeltin** [comment]
Looks like that error occurs when there are any variables assigned to a Hero type. It seems like this could also occur with Colors, Buttons, Gamemodes, and Maps.

**Comment by CactusPuppy** [comment]
The Debugger is no longer supported.
