### ISSUE TITLE
map.GetPath(); doesn't return a value, or is not implemented

### ISSUE THREAD

**Issue by Preciseful** [ItsDeltin/Overwatch-Script-To-Workshop#402]
this is the implemented error only: 

> An exception was thrown while translating to workshop.
System.NotImplementedException: The method or operation is not implemented.
   at Deltin.Deltinteger.Pathfinder.PathfindVectorPath.get_LoopCondition() in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Pathfinder\Algorithm Builder\PathmapPathfinderInfo.cs:line 312
   at Deltin.Deltinteger.Pathfinder.PathfindAlgorithmBuilder.Get() in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Pathfinder\Algorithm Builder\Algorithm.cs:line 43
   at Deltin.Deltinteger.Pathfinder.PathmapClass.<get_GetPath>b__56_0(ActionSet actionSet, MethodCall methodCall) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Pathfinder\Classes\PathmapClass.cs:line 320
   at Deltin.Deltinteger.Parse.ExpressionTree.ParseTree(ActionSet actionSet, Boolean expectingValue) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\ExpressionTree.cs:line 216
   at Deltin.Deltinteger.Parse.ExpressionTree.Translate(ActionSet actionSet) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\ExpressionTree.cs:line 171
   at Deltin.Deltinteger.Parse.BlockAction.Translate(ActionSet actionSet) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Block.cs:line 37
   at Deltin.Deltinteger.Parse.DeltinScript.ToWorkshop(Func`2 addRules) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Translate.cs:line 260
   at Deltin.Deltinteger.Parse.DeltinScript..ctor(TranslateSettings translateSettings) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Translate.cs:line 57

**Comment by ctzndwn** [comment]
I'm getting something similar.


An exception was thrown while parsing.
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at Deltin.Deltinteger.Parse.DefineContextHandler.GetComponents(VariableComponentCollection componentCollection) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Variables\Builders\ContextHandlers.cs:line 40
   at Deltin.Deltinteger.Parse.VarBuilder.GetVar() in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Variables\Builders\VarBuilder.cs:line 78
   at Deltin.Deltinteger.Parse.ParameterProvider.GetParameterProviders(ParseInfo parseInfo, Scope methodScope, List`1 context, Boolean subroutineParameter) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Parameters\ParameterProvider.cs:line 69
   at Deltin.Deltinteger.Parse.DefinedMethodProvider..ctor(ParseInfo parseInfo, IScopeHandler scopeProvider, FunctionContext context, IDefinedTypeInitializer containingType) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Functions\User\DefinedMethod.cs:line 92
   at Deltin.Deltinteger.Parse.DeltinScript.Translate() in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Translate.cs:line 199
   at Deltin.Deltinteger.Parse.DeltinScript..ctor(TranslateSettings translateSettings) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Translate.cs:line 57
   at Deltin.Deltinteger.LanguageServer.DocumentHandler.Update(Document item) in C:\Users\HDdel\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Language Server\DocumentHandler.cs:line 189
