### ISSUE TITLE
won't output workshop code if any kind of "for loop" is in the code

### ISSUE THREAD

**Issue by ToonNoah** [ItsDeltin/Overwatch-Script-To-Workshop#452]
instead of showing the workshop code in the output, the output contains an error:

![image](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/assets/36281513/8378d228-71cb-4b59-87e9-3195c83d19b7)

```
An exception was thrown while translating to workshop.
System.InvalidCastException: Unable to cast object of type 'Deltin.Deltinteger.Parse.TargetGettable' to type 'Deltin.Deltinteger.Parse.IndexReference'.
   at Deltin.Deltinteger.Parse.ForAction.TranslateAutoFor(ActionSet actionSet) in /home/runner/work/Overwatch-Script-To-Workshop/Overwatch-Script-To-Workshop/Deltinteger/Deltinteger/Parse/Loops.cs:line 264
   at Deltin.Deltinteger.Parse.ForAction.Translate(ActionSet actionSet) in /home/runner/work/Overwatch-Script-To-Workshop/Overwatch-Script-To-Workshop/Deltinteger/Deltinteger/Parse/Loops.cs:line 214
   at Deltin.Deltinteger.Parse.BlockAction.Translate(ActionSet actionSet) in /home/runner/work/Overwatch-Script-To-Workshop/Overwatch-Script-To-Workshop/Deltinteger/Deltinteger/Parse/Block.cs:line 36
   at Deltin.Deltinteger.Parse.DeltinScript.ToWorkshop(Func`2 addRules) in /home/runner/work/Overwatch-Script-To-Workshop/Overwatch-Script-To-Workshop/Deltinteger/Deltinteger/Parse/Translate.cs:line 265
   at Deltin.Deltinteger.Parse.DeltinScript..ctor(TranslateSettings translateSettings) in /home/runner/work/Overwatch-Script-To-Workshop/Overwatch-Script-To-Workshop/Deltinteger/Deltinteger/Parse/Translate.cs:line 63
```

**Comment by pharingWell** [comment]
Not a valid bug description, as discussed in workshop-help. Something else in your code is causing that
