### ISSUE TITLE
[BUG] Unable to use Pathfinding functionality

### ISSUE THREAD

**Issue by Erythritee** [ItsDeltin/Overwatch-Script-To-Workshop#457]
![image](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/assets/71497207/5be2a06c-dd20-40c0-a072-0ed6bab66dfe)

The file opened in the image is the example file in repository
https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/blob/master/Examples/Jump-pad%20pathfinding/Map.pathmap

Here is the complete error：
```
An exception was thrown while translating to workshop.
System.Collections.Generic.KeyNotFoundException: The given key 'Deltin.Deltinteger.Parse.InternalVar' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Deltin.Deltinteger.Parse.ObjectVariable.GetGettable(ToWorkshop toWorkshop, IWorkshopTree reference) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Types\Classes\ObjectVariable.cs:line 47
   at Deltin.Deltinteger.Parse.ObjectVariable.GetGettable(ActionSet actionSet, IWorkshopTree reference) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Types\Classes\ObjectVariable.cs:line 41
   at Deltin.Deltinteger.Parse.ObjectVariable.SetWithReference(ActionSet actionSet, IWorkshopTree reference, IWorkshopTree value, Element[] index) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Types\Classes\ObjectVariable.cs:line 29
   at Deltin.Deltinteger.Pathfinder.PathmapClass.New(ActionSet actionSet, NewClassInfo newClassInfo) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Pathfinder\Classes\PathmapClass.cs:line 176
   at Deltin.Deltinteger.Parse.SelfContainedClassInstance.New(ActionSet actionSet, NewClassInfo classInfo) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Types\Classes\Internal\SelfContainedClass.cs:line 93
   at Deltin.Deltinteger.Parse.ClassType.New(ActionSet actionSet, Constructor constructor, WorkshopParameter[] parameters) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Types\Classes\ClassType.cs:line 76
   at Deltin.Deltinteger.Parse.CreateObjectAction.Parse(ActionSet actionSet) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Types\Semantics\CreateObjectAction.cs:line 64
   at Deltin.Deltinteger.Parse.IVariableDefault.<>c__DisplayClass2_0.<FromExpression>b__0(ActionSet actionSet) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Variables\GettableAssigners\IVariableDefault.cs:line 14
   at Deltin.Deltinteger.Parse.IVariableDefault.VariableDefault.Deltin.Deltinteger.Parse.IVariableDefault.GetDefaultValue(ActionSet actionSet) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Variables\GettableAssigners\IVariableDefault.cs:line 19
   at Deltin.Deltinteger.Parse.DataTypeAssigner.GetResult(GettableAssignerValueInfo info) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Variables\GettableAssigners\DataTypeAssigner.cs:line 18
   at Deltin.Deltinteger.Parse.IGettableAssigner.GetValue(GettableAssignerValueInfo info) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Variables\GettableAssigners\IGettableAssigner.cs:line 86
   at Deltin.Deltinteger.Parse.DeltinScript.ToWorkshop(Func`2 addRules) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Translate.cs:line 249
   at Deltin.Deltinteger.Parse.DeltinScript..ctor(TranslateSettings translateSettings) in F:\OneDrive\Projects\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Translate.cs:line 63
```

**Comment by ItsDeltin** [comment]
Thank you for the report!
The new pathfinding system can be found at https://workshop.codes/pathfinder, which I recommend using over the `Pathmap` class.
