### ISSUE TITLE
Frequent Crashes as of v0.3.15

### ISSUE THREAD

**Issue by TforTrevor** [ItsDeltin/Overwatch-Script-To-Workshop#46]
The parser crashes frequently when using enums as of v0.3.15.
```
C:\Users\Trevor\Desktop\Release>start /WAIT /B "" "Deltinteger.exe" "-langserver
" "-port 9145 9146"

C:\Users\Trevor\Desktop\Release>pause
Press any key to continue . . . [:] Overwatch Script To Workshop v0.3.15
[LangServer] Language server started on port 9145 (9146)
[Wiki] Failed to load Workshop Wiki: The underlying connection was closed: An unexpected error occurred on a send.

Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at Deltin.Deltinteger.Elements.EnumData.ToElement(EnumMember enumMember) in C:\Users\HDdel\Documents\GitHub\Overwatch-Workshop-Text\Deltinteger\Deltinteger\Elements\Enums.cs:line 90
   at Deltin.Deltinteger.Parse.TranslateRule.ParseParameters(ScopeGroup scope, ParameterBase[] parameters, Node[] values, String methodName, Location methodRange) in C:\Users\HDdel\Documents\GitHub\Overwatch-Workshop-Text\Deltinteger\Deltinteger\Parse\TranslateRule.cs:line 380
   at Deltin.Deltinteger.Parse.TranslateRule.ParseMethod(ScopeGroup scope, MethodNode methodNode, Boolean needsToBeValue) in C:\Users\HDdel\Documents\GitHub\Overwatch-Workshop-Text\Deltinteger\Deltinteger\Parse\TranslateRule.cs:line 418
   at Deltin.Deltinteger.Parse.TranslateRule.ParseStatement(ScopeGroup scope, Node statement, IndexedVar returnVar) in C:\Users\HDdel\Documents\GitHub\Overwatch-Workshop-Text\Deltinteger\Deltinteger\Parse\TranslateRule.cs:line 637
   at Deltin.Deltinteger.Parse.TranslateRule.ParseBlock(ScopeGroup scopeGroup, BlockNode blockNode, Boolean fulfillReturns, IndexedVar returnVar) in C:\Users\HDdel\Documents\GitHub\Overwatch-Workshop-Text\Deltinteger\Deltinteger\Parse\TranslateRule.cs:line 625
   at Deltin.Deltinteger.Parse.TranslateRule..ctor(String file, RuleNode ruleNode, ScopeGroup root, ParsingData parserData) in C:\Users\HDdel\Documents\GitHub\Overwatch-Workshop-Text\Deltinteger\Deltinteger\Parse\TranslateRule.cs:line 39
   at Deltin.Deltinteger.Parse.ParsingData..ctor(String file, String content) in C:\Users\HDdel\Documents\GitHub\Overwatch-Workshop-Text\Deltinteger\Deltinteger\Parse\Parse.cs:line 216
   at Deltin.Deltinteger.LanguageServer.Server.ParseDocument(String input, Int32 clientPort) in C:\Users\HDdel\Documents\GitHub\Overwatch-Workshop-Text\Deltinteger\Deltinteger\LanguageServer.cs:line 135
   at Deltin.Deltinteger.LanguageServer.Server.RequestLoop(Int32 serverPort, Int32 clientPort) in C:\Users\HDdel\Documents\GitHub\Overwatch-Workshop-Text\Deltinteger\Deltinteger\LanguageServer.cs:line 68
   at Deltin.Deltinteger.Program.Main(String[] args) in C:\Users\HDdel\Documents\GitHub\Overwatch-Workshop-Text\Deltinteger\Deltinteger\Program.cs:line 39```

**Comment by ItsDeltin** [comment]
Fixed in [v0.3.15.1](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.3.15.1)
