### ISSUE TITLE
Decompiling a double not throws an exception

### ISSUE THREAD

**Issue by SlenderFox** [ItsDeltin/Overwatch-Script-To-Workshop#491]
As title states, decompiling an action with a double not throws an error.
![image](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/assets/36467674/e5e46aca-8bcb-446b-90da-8cebeba5974b)
Example rule ^
Here is the error message
```
An exception was thrown while decompiling: System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.PopOperator() in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 1013
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.PushOperator(TTEOperator op) in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 976
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.Expression(ITTEExpression& expr, Boolean root) in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 683
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.Expression(ITTEExpression& expr, Boolean root) in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 684
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.ContainExpression(ITTEExpression& expr) in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 721
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.Function(ElementBaseJson func, FunctionExpression& expr) in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 640
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.Function(Boolean actions, FunctionExpression& expr) in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 560
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.Action(ITTEAction& action) in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 537
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.ActionGroup(List`1& actionList) in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 469
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.Rule(TTERule& rule) in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 372
   at Deltin.Deltinteger.Decompiler.TextToElement.ConvertTextToElement.Get() in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Decompiler\TextToElement\TextToElement.cs:line 74
   at Deltin.Deltinteger.LanguageServer.StdServer.<>c.<AddRequests>b__11_2() in D:\Projects_Local\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Language Server\StdServer.cs:line 96
   ```

**Comment by CactusPuppy** [comment]
Probably related to #249
