### ISSUE TITLE
Repeated null reference exceptions

### ISSUE THREAD

**Issue by TrueCP6** [ItsDeltin/Overwatch-Script-To-Workshop#90]
Exception:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Deltin.Deltinteger.LanguageServer.Server.GetAutocomplete(String json) in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Language Server\Server.cs:line 281
   at Deltin.Deltinteger.LanguageServer.Server.RequestLoop(Int32 serverPort) in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Language Server\Server.cs:line 66
   at Deltin.Deltinteger.Program.Main(String[] args) in C:\Users\Deltin\Documents\GitHub\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Program.cs:line 41
```
Code:
```
define globalvar Marks = [];

method SetMarks()
{
    Marks[0] = RandomValueInArray(AllPlayers(Team.Team1));
    Marks[1] = RandomValueInArray(AllPlayers(Team.Team2));
}

rule:"Mark"
if ()
{

}
```

**Comment by ItsDeltin** [comment]
Does not occur in the [General-Rework](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/commits/General-Rework) branch, which heavily improves the language server. The new language server is coming in the next release.

**Comment by ItsDeltin** [comment]
[v1.0-prerelease-1](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.0)
